### PR TITLE
Call widget.resize in more situations

### PR DESCRIPTION
**Pull request by jcheng5**
e.g. rstudio/leaflet wasn't working if you had a widget like this:

```{r}
library(leaflet)
leaflet() %>% addTiles()
```

in an rmarkdown ioslide on the 5th slide and the slide deck was
showing slide 1 when the browser loaded it.

I'll submit more repro cases in the pull request.

### CODE REVIEW

**Comment by jjallaire** [comment]
This looks good to me. @ramnathv ?

**Comment by ramnathv** [comment]
This looks good to me. Although this makes me wonder, if we need and can build a more generic solution that will allow resizing to be triggered by other frameworks/widgets. Ideally, `htmlwidgets` should provide a mechanism that `ioslides` can take advantage of to postpone rendering till the particular slide is displayed. We can merge this in, and think about that for the future. @jcheng5 @jjallaire any thoughts on this?

**Comment by jcheng5** [comment]
I think the hooks are there already, if you don't want to render when you're not visible you can have your widget's `renderValue` callback not do anything when the element's offsetWidth/offsetHeight are 0. And then have your `resize` callback call `renderValue`, as in previous examples we've looked at.

However, we still need to make sure `resize` gets called at the appropriate time, which wasn't the case with ioslides (at least not in all scenarios) without this PR. One idea JJ and I batted around earlier today was triggering the window's resize event from ioslides. The shown/hidden events that are subscribed in this PR would also work, but those depend on jQuery to work cross platform AFAICT.

**Comment by jcheng5** [comment]
Sorry for not delivering the promised examples yet. I am seeing one weird behavior that may be due to just a weird version of Shiny installed, but I want to make sure.

**Comment by jcheng5** [comment]
Two examples:
https://gist.github.com/jcheng5/aff6ef5dbb76bb140f30

A Leaflet bugfix is also needed to fix this bug. I've just merged it into master, so `devtools::install_github('rstudio/leaflet')` should do it.

The "Shiny map" slide should render fine even without this fix; the others do need the fix.

To repro the problem, make sure when the browser loads the slide deck, that it's starting at slide 1.

**Comment by ramnathv** [comment]
Thanks @jcheng5. I won't be able to test this till late next week. But I am good with merging this since you and @jjallaire have tested it, and it only modifies behavior specific to `ioslides` minimizing the chances of any regression.

**Comment by timelyportfolio** [comment]
possibly related to #102; +1 for more resize

**Pull request merged**
