### PR TITLE
Fix a bug with </script> appearing in widget data

### PR DESCRIPTION
**Pull request by jcheng5**
See comment in the commit.

### CODE REVIEW

**Comment by ramnathv** [comment]
@jcheng5 I presume this fixes a security bug?

**Comment by jcheng5** [comment]
No, I don't think it's security related--good guess though! If `</script>` appears in the widget data, it'll simply break that data's ability to load.

I'm pulling this out of the air, forgive any mistakes:

```html
<script type="application/json" for="widget-1234">
{
  width: null,
  height: null,
  x: {
    title: "Why </script> is problematic"
  }
}
</script>
```

When widget-1234 goes to load/parse its JSON, it'll fail, since the browser will consider the script block ended right after `title: "Why `.

**Comment by ramnathv** [comment]
Got it. I will test tonight to make sure that it doesn't break anything and merge.

**Comment by yihui** [comment]
FWIW, Joe has used this in the leaflet docs: http://rstudio.github.io/leaflet/ I don't see anything wrong there (look for `\u003c` in the HTML source). So I guess this PR should be good to go. It is a little unfortunate we didn't merge it for the 0.4 release.

**Comment by ramnathv** [comment]
Sorry for missing this one.

**Comment by yihui** [comment]
Thanks. Can you also bump the version?

**Comment by ramnathv** [comment]
Done! Thanks

**Pull request merged**
