### PR TITLE
Support shown/hidden.bs.collapse events for Bootstrap collapse

### PR DESCRIPTION
**Pull request by yihui**
Fixes rstudio/DT#204

### CODE REVIEW

**Comment by ramnathv** [comment]
This looks good to me. However, instead of increasing the list of events that trigger the `resizeHandler`, cant we add a HTMLWidgets method that allows one to register custom events that trigger the resize handler? This could be a property on the widget that widget authors can customize? Or maybe it could be specific to a widget instance, so that a user can register custom events. @jcheng5 @jjallaire @timelyportfolio  what do you think?

**Comment by jjallaire** [comment]
I agree that it would be nice for widgets to be able to provide a list of jquery event selectors which result in a resize, however given the number of widgets (now 30 on CRAN alone!) and the fact that the cases where a resize is required are to a large extent enumerable I think it's better if we can handle this centrally so widgets don't have to discover these cases from first principles.

**Comment by ramnathv** [comment]
Sounds good @jjallaire and @yihui

**Comment by timelyportfolio** [comment]
I have been thinking a lot about this lately, and I hate having to inject framework-specific event handlers in `htmlwidgets` code, but I can't think of any way around it.  Perhaps, we could work on separating these out some way, so they are clear.

**Pull request merged**
